import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */
const sidebars: SidebarsConfig = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  documentationSidebar: [
    'documentation/index',
    {
      type: 'category',
      label: 'AI',
      items: [
        {
          type: 'autogenerated',
          dirName: 'documentation/ai', 
        },
      ],
    },
    {
      type: 'category',
      label: 'Datastorage',
      items: [
        {
          type: 'autogenerated',
          dirName: 'documentation/datastorage', 
        },
      ],
    },
    {
      type: 'category',
      label: 'Mikroslužby',
      items: [
        {
          type: 'autogenerated',
          dirName: 'documentation/microservices', 
        },
      ],
    },
    {
      type: 'category',
      label: 'UX',
      items: [
        {
          type: 'autogenerated',
          dirName: 'documentation/ux', 
        },
      ],
    },
  ],

  sprintSidebar: [
    'sprints/index',
    {
      type: 'category',
      label: 'Retrospektíva 1. šprintu',
      items: [
        {
          type: 'autogenerated',
          dirName: 'sprints/01_sprint',
        },
      ],
    },
    {
      type: 'category',
      label: 'Retrospektíva 2. šprintu',
      items: [
        {
          type: 'autogenerated',
          dirName: 'sprints/02_sprint',
        },
      ],
    },
  ],

  /**docs: [
  //  'index',
    {
      type: 'category',
      label: 'Retrospektíva 1. šprintu',
      items: [
        {
          type: 'autogenerated',
          dirName: '02_first-sprint',
        },
      ],
    },
    //HERE ADD ANOTHER CATHEGORIES FOR THE SIDEBAR
    
    // {type: 'autogenerated', dirName: '.'}
  ],*/

  // But you can create a sidebar manually
  /*
  tutorialSidebar: [
    'intro',
    'hello',
    {
      type: 'category',
      label: 'Tutorial',
      items: ['tutorial-basics/create-a-document'],
    },
  ],
   */
};

export default sidebars;
